version: '2'
services:
  postgres:
    image: postgres:13
    container_name: postgres-user-api
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  app:
    build: ./src
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - postgres